/* eslint-disable */

// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.



const awsmobile = {

    "aws_project_region": "us-west-1",

    "aws_cognito_identity_pool_id": "us-west-1:f3c0d7df-347f-40fd-a674-1b7b7db71074",

    "aws_cognito_region": "us-west-1",

    "aws_user_pools_id": "us-west-1_hv7y0dlGR",

    "aws_user_pools_web_client_id": "4hbmjmvruiej7mqffhilqftoff",

    "oauth": {},

    "aws_cognito_username_attributes": [

        "EMAIL"

    ],

    "aws_cognito_social_providers": [],

    "aws_cognito_signup_attributes": [

        "EMAIL"

    ],

    "aws_cognito_mfa_configuration": "OFF",

    "aws_cognito_mfa_types": [

        "SMS"

    ],

    "aws_cognito_password_protection_settings": {

        "passwordPolicyMinLength": 8,

        "passwordPolicyCharacters": []

    },

    "aws_cognito_verification_mechanisms": [

        "EMAIL"

    ]

};




export default awsmobile;